from tkinter import N


greetmsg = "Друзья!\n\nВы хотите развить умение общаться на английском языке и интересные и современные темы, а также потренироваться в выполнении заданий в формате ЕГЭ? Тогда вам сюда!"
lessonmsg = "Начало урока\n\nПеред тем, как урок начнётся, давайте отгадаем тему урока.\n\nunscramble the phrase - nrgaeid dan piaskneg obatu ceecsin "
aimmsg = "The aim of the lesson is to teach you to select the necessary information from a text for aural comprehension and use it in explanatory monologues of your own. You are going to discuss some scientific issues."
task5 = "Scientists have developed a tiny camera that can be put on the back of a beetle. The camera can record where the bug goes. This will give the scientists a bug's-eye view of the world. The researchers want to use the camera to explore places never seen before. Researcher Vikram Iyer explained why the camera could be useful. He said: "Insects can traverse rocky environments, which is really challenging for robots to do at this scale. So this system can also help us out by letting us see or collect samples from hard-to-navigate spaces." Mr Iyer is excited to see what the cameras record. He said: ""This is the first time that we've had a first-person view from the back of a beetle while it's walking around.""\n\nThe scientists are from the University of Washington in the USA. They wanted to develop a camera light enough for bugs to wear. It weighs just 250 milligrams. Their wireless camera records images at up to five frames per second. A researcher said: ""We have created a low-power, low-weight, wireless camera system that can capture a first-person view of what's happening from an actual live insect."" He said one of the biggest challenges when making the camera was the battery. It had to be very small and very light, with enough power to last a few hours. The researchers stressed that no beetles were hurt in their tests and that all the insects ""lived for at least a year"" after the experiments finished."
task5q = "QUESTIONS\n\n1.Where did the article say the camera can record?\n2.What places do researchers want to explore?\n3.What kind of environments did a researcher say insects can traverse?\n4.What did the researcher say insects could collect?\n5.What kind of view did the researcher say we would have?\n6.Where are the scientists from?\n7.How much does the camera weigh?\n8.How many frames per second can the camera record?\n9.What was the biggest challenge regarding the camera?\n10.For how long did the beetles live after the experiments finished?"
task6 = "Task 6. Communication. Express your opinion concerning some of the issues given below. You are to answer each question in at least two sentences. Work in pairs. Ask your partner any five questions."
task6q = "Did you like reading this article? Why/not?Would you like to wear a tiny camera?\nWould you like to work as a beetle researcher?\nHow might this technology help beetles?\nHow might this technology help humans?\nIs it ethical to do use beetles in experiments?\nWhat would people see every day if you wore a camera?\nWhat questions would you like to ask the researchers?\n"
refl = "Reflection: Translate and go on speaking (2 sentences, in chain)\n\nСегодня я узнал…\nНа уроке я научился…\nМне было трудно…\nМне было непонятно…\nТеперь я знаю, что…\nМеня удивило…\nЯ бы хотел узнать, почему…\n"
